### ISSUE TITLE
Handling of xy in convolutional layers

### ISSUE THREAD

**Issue by Quasimondo** [Evolving-AI-Lab/synthesizing#1]
Looking at the code inside of act_max.py it appears to me that the way the neurons get activated in convolutional layers is a bit of a shortcut and will miss most of them. It looks like only the diagonal ones are accessed since xy is the same for x and y:

```
# Move in the direction of increasing activation of the given neuron
  if end in fc_layers:
    one_hot.flat[unit] = 1.
  elif end in conv_layers:
    one_hot[:, unit, xy, xy] = 1.
  else:
    raise Exception("Invalid layer type!")
```

I made a quick fix which seems to work, which treats the xy as an index and converts it to a column/row representation - I'm not sure if this makes sense, but it does return results that look reasonable:

```
# Move in the direction of increasing activation of the given neuron
  if end in fc_layers:
    one_hot.flat[unit] = 1.
  elif end in conv_layers:
    one_hot[:, unit, xy % one_hot.shape[2], int(xy/one_hot.shape[2])] = 1.
  else:
    raise Exception("Invalid layer type!")
```

further down in that function another fix is required:

```
# Check the activations
  if end in fc_layers:
    fc = acts[end][0]
    best_unit = fc.argmax()
    obj_act = fc[unit]

  elif end in conv_layers:
    fc = acts[end][0, :, xy % acts[end].shape[2] , int(xy/acts[end].shape[2])]
    best_unit = fc.argmax()
    obj_act = fc[unit]

```

**Comment by anguyen8** [comment]
@Quasimondo : Yes, for our project, I conflate x, y into one single xy variable, but for general use, they should be best separated as you mention. Will try to separate them at some point.
