### ISSUE TITLE
Weights link not available

### ISSUE THREAD

**Issue by javierrodenas** [Evolving-AI-Lab/synthesizing#13]
Hello,

I am trying to run the code but I can't download the weights. The link seems to be deactivatex.

cd nets/upconv && ./download.sh or the direct link doesn't respond.

Can you help with this problem?

Thank you in advance.

**Comment by anguyen8** [comment]
@javierrodenas Thanks for your note!

I've updated the path (the URL now is https:// instead of http) in https://github.com/Evolving-AI-Lab/synthesizing/blob/master/nets/upconv/download.sh

It should work now. Let me know if it does not. 

Thanks!
