### ISSUE TITLE
Details about training the generator

### ISSUE THREAD

**Issue by nitnelave** [Evolving-AI-Lab/synthesizing#2]
Hello,

I'm trying to adapt your code for a different network (a regression), and I have trouble training the generator network. I'm using http://arxiv.org/abs/1602.02644 as a reference, but I have trouble finding a good combination of generator architecture, discriminant architecture, and hyper parameters.

Would you be open to shared some details of how you trained the generator?

Thanks,

**Comment by anguyen8** [comment]
@nitnelave : Hi, our experience so far is we get the best results visualizing network _E_ if we use the generator that is trained (following the paper you cited above) to invert _E_. 

Some code and more info about training the generator can be found here:
http://lmb.informatik.uni-freiburg.de/people/dosovits/code.html

It's hard to answer exactly your question as it's an empirical question. Have you tried training a generator to invert your net via the code above?
