### ISSUE TITLE
How to increase output resolution?

### ISSUE THREAD

**Issue by MateSteinforth** [Evolving-AI-Lab/synthesizing#3]
How to increase the resolution of the output images?

**Comment by anguyen8** [comment]
@MateSteinforth : The size of the output image is fixed to be the size of the input to the CNNs (e.g. 227x227 for AlexNet, or 224x224 for GoogLeNet).

You could try either of the following:
1. Train new networks that can handle larger image sizes
2. Create a large canvas and optimize fixed chunks of 227x227 (e.g. like Google's DeepDream)
