### ISSUE TITLE
Activating 2 neurons at the same time (feature)

### ISSUE THREAD

**Issue by adamhrv** [Evolving-AI-Lab/synthesizing#4]
This is not an issue, but a feature request. Is there code available for visualizing 2 (or more) neurons at the same time? 

I'd like to explore the section of your paper about using 2, or more, neurons to generate a single image, for example volcano (n09472597 volcano)  + Candle (n02948072 candle, taper, wax light). 

Very cool project.

**Comment by anguyen8** [comment]
@adamhrv : we talked via email, but I'll reply here in case others have the same question.

I'll try to publish the code/params for 2 or more neurons in a near future.
