### ISSUE TITLE
Output size ?

### ISSUE THREAD

**Issue by kenkroft** [Evolving-AI-Lab/synthesizing#5]
Hello ! I totally love this code, thank you so much for putting this together. But I just have a question, how to up the output size ? I just bought a very fast computer and I would like to have High rez results !

That would be amazing, thanks in advance !

**Comment by anguyen8** [comment]
@kenkroft Hi, you would have to train your own Upconvnet and the net you want to visualize on images of the larger size you want. Currently this output size is already the state of the art (256x256).
